name: 'Artia-GitHub-Issue-Gera-Atividade'
description: 'Ação para gerar uma Atividade a partir de um issue'
inputs:
  organizationId: #id da organização
    description: 'id da organização no Artia'
    require: true
    default: 111402
  accountId: # id do grupo de trabalho
    description: 'id do grupo de trabalho'
    required: true
    default: 123
  folderId: #ID da pasta ou do projeto para criar uma atividade.
    description: 'pasta ou projeto para criar uma atividade'
    required: false
    default: '123'
  creatorEmail: #email cadastrado no artia com acesso ao projeto/atividade.
    description: 'email cadastrado no artia com acesso ao projeto e atividade'
    required: true
    default: 'api@artia.com'
  creatorPassword: #senha para gerar token de acesso.
    description: 'senha utilizada para gerar token do artia'
    required: true
    default: '123'
outputs:
  time: # id da saída
    description: 'Atividade criada'
runs:
  using: 'node12'
  main: 'dist/index.js'
